"""Initial2345 Migration

Revision ID: 75210a4b5553
Revises: b770ee853818
Create Date: 2019-03-01 11:41:47.913060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75210a4b5553'
down_revision = 'b770ee853818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_content', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'pitch_content')
    # ### end Alembic commands ###
