"""Initial123 Migration

Revision ID: b770ee853818
Revises: 216254a7784f
Create Date: 2019-03-01 11:39:55.312146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b770ee853818'
down_revision = '216254a7784f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'pitch_title')
    # ### end Alembic commands ###
